# Generated by Django 5.0.1 on 2024-11-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imagen',
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_url',
            field=models.URLField(default='https://fdn2.gsmarena.com/vv/bigpic/dummy.jpg', max_length=500),
        ),
    ]
